// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.ContextEFs;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextEF))]
    [Migration("20251027013227_AjusteDeleteBehavior")]
    partial class AjusteDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.Property<int>("CodigoToDoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idToDoItem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoToDoItem"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoToDoItemPai")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CodigoToDoItem");

                    b.HasIndex("CodigoToDoItemPai");

                    b.ToTable("ToDoItem", (string)null);
                });

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.HasOne("Domain.ToDoItems.ToDoItem", "ToDoItemPai")
                        .WithMany("SubTarefas")
                        .HasForeignKey("CodigoToDoItemPai")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ToDoItemPai");
                });

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.Navigation("SubTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
