// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.ContextEFs;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextEF))]
    [Migration("20260305032955_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idauditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("acao");

                    b.Property<string>("Alteracoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alteracoes");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataocorrencia");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entidade");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("identidade");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idusuario");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_auditoria_data");

                    b.HasIndex("IdEntidade")
                        .HasDatabaseName("ix_auditoria_identidade");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_auditoria_usuario");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lembrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLembrete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoTarefa")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DataDisparo")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarefa");

                    b.ToTable("Lembrete", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtarefa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<int?>("CodigoTarefaPai")
                        .HasColumnType("int")
                        .HasColumnName("idtarefapai");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("data_criacao");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarefaPai");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("Lembretes")
                        .HasForeignKey("CodigoTarefa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "TarefaPai")
                        .WithMany("SubTarefas")
                        .HasForeignKey("CodigoTarefaPai")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TarefaPai");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Navigation("Lembretes");

                    b.Navigation("SubTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
