// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.ContextEFs;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextEF))]
    [Migration("20260111011726_adicionar_coluna_lembrete")]
    partial class adicionarcolunalembrete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Lembretes.Lembrete", b =>
                {
                    b.Property<Guid>("CodigoLembrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLembrete");

                    b.Property<TimeSpan>("Antecedencia")
                        .HasColumnType("time")
                        .HasColumnName("antecedencia");

                    b.Property<int>("CodigoToDoItem")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_de_envio");

                    b.Property<DateTime>("DataDoEnvio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_do_envio");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("texto");

                    b.HasKey("CodigoLembrete");

                    b.HasIndex("CodigoToDoItem");

                    b.ToTable("Lembrete", (string)null);
                });

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.Property<int>("CodigoToDoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtodoitem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoToDoItem"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<int?>("CodigoToDoItemPai")
                        .HasColumnType("int")
                        .HasColumnName("idtodoitempai");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("CodigoToDoItem");

                    b.HasIndex("CodigoToDoItemPai");

                    b.ToTable("ToDoItem", (string)null);
                });

            modelBuilder.Entity("Domain.Lembretes.Lembrete", b =>
                {
                    b.HasOne("Domain.ToDoItems.ToDoItem", "ToDoItem")
                        .WithMany("Lembretes")
                        .HasForeignKey("CodigoToDoItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoItem");
                });

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.HasOne("Domain.ToDoItems.ToDoItem", "ToDoItemPai")
                        .WithMany("SubTarefas")
                        .HasForeignKey("CodigoToDoItemPai")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ToDoItemPai");
                });

            modelBuilder.Entity("Domain.ToDoItems.ToDoItem", b =>
                {
                    b.Navigation("Lembretes");

                    b.Navigation("SubTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
