// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.ContextEFs;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ContextEF))]
    partial class ContextEFModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idauditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("acao");

                    b.Property<string>("Alteracoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alteracoes");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataocorrencia");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entidade");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("identidade");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idusuario");

                    b.HasKey("Id");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_auditoria_data");

                    b.HasIndex("IdEntidade")
                        .HasDatabaseName("ix_auditoria_identidade");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_auditoria_usuario");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lembrete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLembrete");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoTarefa")
                        .HasColumnType("int")
                        .HasColumnName("CodigoTarefa");

                    b.Property<DateTimeOffset>("DataDisparo")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DataDisparo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descricao");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarefa");

                    b.ToTable("Lembrete", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ParamGeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idparamgeral");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArquivamentoAutomaticoTarefasConcluidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("arquivamento_automatico_tarefas_concluidas");

                    b.Property<bool>("ArquivarTarefasConcluidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("arquivar_tarefas_concluidas");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<TimeSpan>("HorarioResumoDiario")
                        .HasColumnType("time")
                        .HasColumnName("horario_resumo_diario");

                    b.Property<int>("ListagemPadraoDeTarefas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("listagem_padrao_de_tarefas");

                    b.Property<bool>("NotificarTarefasAntesDoInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("notificar_tarefas_antes_do_inicio");

                    b.Property<int>("PrimeiroDiaDaSemana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("primeiro_dia_da_semana");

                    b.Property<int>("QuantidadeDateTimeAntesDoInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade_datetime_antes_do_inicio");

                    b.Property<int>("QuantidadeDiasParaArquivamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade_dias_para_arquivamento");

                    b.Property<bool>("ReceberNotificacaoPorEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("receber_notificacao_por_email");

                    b.Property<bool>("ReceberNotificacaoPorWhatsApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("receber_notificacao_por_whatsapp");

                    b.Property<bool>("ReceberResumoDiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("receber_resumo_diario");

                    b.Property<bool>("ReforcarlembreteNoProprioDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("reforcar_lembrete_no_proprio_dia");

                    b.Property<int>("TelaInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tela_inicial");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("telefone");

                    b.Property<int>("Unidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("unidade_antes_do_inicio");

                    b.HasKey("Id");

                    b.ToTable("ParamGeral", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtarefa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<int?>("CodigoTarefaPai")
                        .HasColumnType("int")
                        .HasColumnName("idtarefapai");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataTarefa")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_tarefa");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("hora_fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int")
                        .HasColumnName("prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarefaPai");

                    b.ToTable("Tarefa", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Repository.QueryModels.Tarefas.HistoricoTarefaItemQueryModel", b =>
                {
                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acao");

                    b.Property<string>("Alteracoes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alteracoes");

                    b.Property<DateTimeOffset>("DataOcorrencia")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dataocorrencia");

                    b.Property<string>("EscopoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("escopo_evento");

                    b.Property<int>("IdAuditoria")
                        .HasColumnType("int")
                        .HasColumnName("idauditoria");

                    b.Property<int>("IdTarefaPrincipal")
                        .HasColumnType("int")
                        .HasColumnName("id_tarefa_principal");

                    b.Property<int>("IdTarefaRelacionada")
                        .HasColumnType("int")
                        .HasColumnName("id_tarefa_relacionada");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("idusuario");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("TituloRelacionado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo_relacionado");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "Tarefa")
                        .WithMany("Lembretes")
                        .HasForeignKey("CodigoTarefa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("Domain.Entities.Tarefa", "TarefaPai")
                        .WithMany("SubTarefas")
                        .HasForeignKey("CodigoTarefaPai")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TarefaPai");
                });

            modelBuilder.Entity("Domain.Entities.Tarefa", b =>
                {
                    b.Navigation("Lembretes");

                    b.Navigation("SubTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
