services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - todolist-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - todolist-net

  api:
    container_name: api
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=sqlserver;Database=ToDoItem;User Id=sa;Password=YourStrongPassword123!"
      RabbitMQ__Uri: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "5000:8080"
    networks:
      - todolist-net
    restart: always

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      ConnectionStrings__Default: "Server=sqlserver;Database=ToDoItem;User Id=sa;Password=YourStrongPassword123!"
      RabbitMQ__Uri: "amqp://guest:guest@rabbitmq:5672/"
    networks:
      - todolist-net
    restart: always

networks:
  todolist-net:
    driver: bridge

volumes:
  sqlserver_data:
  rabbitmq_data:
